title: Install-Media-OC
description: This program is use to install macOS from macOS High Sierra 10.13 to macOS Tahoe 26
github: 
  repository_url: https://github.com/chris1111/Install-Media-OC
remote_theme: chris1111/cayman-dark
